const auths = [{
    'hasChild': false,
    'parentOrderNum': null,
    'adminAuth': false,
    'authorityName': '商品',
    'confirmOperation': null,
    'reg': null,
    'authorityCode': 'productRoot',
    'authorityHtmlElement': 'product_list.jsp',
    'orderNum': 101,
    'id': 1,
    'check': false,
    'leaf': false,
    'parameters': null
  },
  {
    'hasChild': true,
    'parentOrderNum': null,
    'adminAuth': false,
    'authorityName': '销售',
    'confirmOperation': null,
    'reg': '^stock.*\\.jsp|^order.*\\.jsp|order_detail_for_stock.jsp|good_select_panel.jsp',
    'authorityCode': 'orderRoot',
    'authorityHtmlElement': null,
    'orderNum': 201,
    'id': 10,
    'check': false,
    'leaf': false,
    'parameters': null
  },
  {
    'hasChild': true,
    'parentOrderNum': 201,
    'adminAuth': false,
    'authorityName': '新建零售单',
    'confirmOperation': null,
    'reg': null,
    'authorityCode': 'orderNew',
    'authorityHtmlElement': 'order_detail_connection.jsp',
    'orderNum': 202,
    'id': 13,
    'check': false,
    'leaf': true,
    'parameters': '{type:\'FOR_SALES\'}'
  },
  {
    'hasChild': true,
    'parentOrderNum': 201,
    'adminAuth': false,
    'authorityName': '零售单',
    'confirmOperation': null,
    'reg': null,
    'authorityCode': 'orderList',
    'authorityHtmlElement': 'order_list.jsp',
    'orderNum': 203,
    'id': 11,
    'check': false,
    'leaf': true,
    'parameters': '{type:\'FOR_SALES\'}'
  },
  {
    'hasChild': true,
    'parentOrderNum': 201,
    'adminAuth': false,
    'authorityName': '零售退货单',
    'confirmOperation': null,
    'reg': null,
    'authorityCode': 'retreatList',
    'authorityHtmlElement': 'retreat_order_list.jsp',
    'orderNum': 204,
    'id': 126,
    'check': false,
    'leaf': true,
    'parameters': '{type:\'RETREAT\'}'
  },
  {
    'hasChild': true,
    'parentOrderNum': 201,
    'adminAuth': false,
    'authorityName': '销售出库单',
    'confirmOperation': null,
    'reg': null,
    'authorityCode': 'salesInventoryOutList',
    'authorityHtmlElement': 'inventory_out_order_list.jsp',
    'orderNum': 205,
    'id': 156,
    'check': false,
    'leaf': true,
    'parameters': '{type:\'INVENTORY_OUT\'}'
  },
  {
    'hasChild': true,
    'parentOrderNum': 201,
    'adminAuth': false,
    'authorityName': '新建销售出库单',
    'confirmOperation': null,
    'reg': null,
    'authorityCode': 'salesInventoryOutDetail',
    'authorityHtmlElement': 'selling_out_details.jsp',
    'orderNum': 206,
    'id': 157,
    'check': false,
    'leaf': true,
    'parameters': null
  }
  /* ,
    {
    	'hasChild': true,
      'parentOrderNum': null,
      'adminAuth': false,
      'authorityName': '库存',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'inventoryRoot',
      'authorityHtmlElement': null,
      'orderNum': 301,
      'id': 15,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
    	'hasChild': true,
      'parentOrderNum': 301,
      'adminAuth': false,
      'authorityName': '库存明细',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'inventoryList',
      'authorityHtmlElement': 'inventory.jsp,used_inventory.jsp',
      'orderNum': 302,
      'id': 16,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 301,
      'adminAuth': false,
      'authorityName': '报损商品管理',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'reportedLossGoods',
      'authorityHtmlElement': 'reported_loss_goods.jsp',
      'orderNum': 303,
      'id': 54,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 301,
      'adminAuth': false,
      'authorityName': '调货配置',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'deployProduct',
      'authorityHtmlElement': 'deploy_right_list.jsp',
      'orderNum': 304,
      'id': 80,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': null,
      'adminAuth': false,
      'authorityName': '财务管理',
      'confirmOperation': null,
      'reg': '^finance.*\\.jsp|^balance.*\\.jsp',
      'authorityCode': 'financeRoot',
      'authorityHtmlElement': null,
      'orderNum': 401,
      'id': 20,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 401,
      'adminAuth': false,
      'authorityName': '流水账管理',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'financeRecord',
      'authorityHtmlElement': 'finance_record.jsp',
      'orderNum': 402,
      'id': 21,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 401,
      'adminAuth': false,
      'authorityName': '新增流水账',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'financeRecordNew',
      'authorityHtmlElement': 'finance_record_new.jsp',
      'orderNum': 403,
      'id': 22,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 401,
      'adminAuth': false,
      'authorityName': '供应商对账',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'financeBalanceRecon',
      'authorityHtmlElement': 'balance_recon.jsp',
      'orderNum': 403,
      'id': 144,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 401,
      'adminAuth': false,
      'authorityName': '向供应商付款',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'financeBalancePay',
      'authorityHtmlElement': 'balance_pay_supplier.jsp',
      'orderNum': 404,
      'id': 145,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': null,
      'adminAuth': false,
      'authorityName': '客户',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'customerRoot',
      'authorityHtmlElement': null,
      'orderNum': 501,
      'id': 24,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '客户列表',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'customerList',
      'authorityHtmlElement': 'customer_list.jsp',
      'orderNum': 502,
      'id': 25,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '客户信息',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'customerDetail',
      'authorityHtmlElement': 'customer_detail_new.jsp,optometry_list.jsp,optometry_edit.jsp,historyOrder_list.jsp,address_list.jsp,address_edit.jsp',
      'orderNum': 503,
      'id': 35,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '客户短信',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'customerSms',
      'authorityHtmlElement': 'customer_sms.jsp',
      'orderNum': 504,
      'id': 36,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '客户邮件',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'customerEmail',
      'authorityHtmlElement': 'customer_email.jsp',
      'orderNum': 505,
      'id': 37,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '新建客户',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'customerNew',
      'authorityHtmlElement': 'customer_new.jsp',
      'orderNum': 506,
      'id': 38,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '供应商列表',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'supplierList',
      'authorityHtmlElement': 'supplier_list.jsp,supplier_detail.jsp',
      'orderNum': 507,
      'id': 58,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '客户信息配置',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'customerConfig',
      'authorityHtmlElement': 'customer_config.jsp',
      'orderNum': 508,
      'id': 83,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '自动短信配置',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'autoSmsConfig',
      'authorityHtmlElement': 'autosms_config.jsp',
      'orderNum': 509,
      'id': 97,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '回访记录编辑',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'clienReviewEdit',
      'authorityHtmlElement': null,
      'orderNum': 510,
      'id': 146,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '回访记录删除',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'clienReviewDelete',
      'authorityHtmlElement': null,
      'orderNum': 511,
      'id': 147,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '强制验证会员身份',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'forceVerifyMember',
      'authorityHtmlElement': null,
      'orderNum': 512,
      'id': 158,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '修改客户积分',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'integralBtn',
      'authorityHtmlElement': null,
      'orderNum': 513,
      'id': 159,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '修改客户成长值',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'growthValueBtn',
      'authorityHtmlElement': null,
      'orderNum': 514,
      'id': 160,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '修改客户储值',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'storedValueBtn',
      'authorityHtmlElement': null,
      'orderNum': 515,
      'id': 161,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '修改客户密保手机',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'modifyMobileBtn',
      'authorityHtmlElement': null,
      'orderNum': 516,
      'id': 162,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '修改客户密码',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'modifyPasswordBtn',
      'authorityHtmlElement': null,
      'orderNum': 517,
      'id': 163,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 501,
      'adminAuth': false,
      'authorityName': '解除第三方账号绑定',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'releaseThirdBtn',
      'authorityHtmlElement': null,
      'orderNum': 518,
      'id': 164,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': null,
      'adminAuth': false,
      'authorityName': '员工',
      'confirmOperation': null,
      'reg': 'employee_.*\\.jsp',
      'authorityCode': 'employeeRoot',
      'authorityHtmlElement': null,
      'orderNum': 550,
      'id': 59,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 550,
      'adminAuth': false,
      'authorityName': '员工列表',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'employeeList',
      'authorityHtmlElement': 'employee_list.jsp',
      'orderNum': 551,
      'id': 60,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 550,
      'adminAuth': false,
      'authorityName': '折扣管理',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'discountList',
      'authorityHtmlElement': 'discount_list.jsp',
      'orderNum': 552,
      'id': 66,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': null,
      'adminAuth': false,
      'authorityName': '报表',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'chartsRoot',
      'authorityHtmlElement': null,
      'orderNum': 601,
      'id': 26,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 601,
      'adminAuth': false,
      'authorityName': '商品销售统计',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'prodSaleSummary',
      'authorityHtmlElement': 'prod_sale_summary.jsp',
      'orderNum': 602,
      'id': 84,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 601,
      'adminAuth': false,
      'authorityName': '员工业绩统计',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'personChievementSummary',
      'authorityHtmlElement': 'person_chievement_summary.jsp',
      'orderNum': 603,
      'id': 86,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 601,
      'adminAuth': false,
      'authorityName': '订单汇总',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'orderSummary',
      'authorityHtmlElement': 'order_summary.jsp',
      'orderNum': 603,
      'id': 87,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 601,
      'adminAuth': false,
      'authorityName': '员工收银报表',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'personCheckout',
      'authorityHtmlElement': 'person_checkout_summary.jsp',
      'orderNum': 604,
      'id': 117,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 601,
      'adminAuth': false,
      'authorityName': '门店收银报表',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'storeCheckout',
      'authorityHtmlElement': 'store_checkout_summary.jsp',
      'orderNum': 605,
      'id': 123,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 601,
      'adminAuth': false,
      'authorityName': '门店收银只允许查看当日',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'storeCheckoutOnlyday',
      'authorityHtmlElement': null,
      'orderNum': 606,
      'id': 136,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 601,
      'adminAuth': false,
      'authorityName': '门店收银环比统计',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'storeCheckoutMonthly',
      'authorityHtmlElement': null,
      'orderNum': 607,
      'id': 138,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 601,
      'adminAuth': false,
      'authorityName': '门店收银区间统计',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'storeCheckoutInterval',
      'authorityHtmlElement': null,
      'orderNum': 608,
      'id': 137,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': null,
      'adminAuth': null,
      'authorityName': '系统设置',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'systemRoot',
      'authorityHtmlElement': null,
      'orderNum': 701,
      'id': 30,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 701,
      'adminAuth': false,
      'authorityName': '支付管理',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'setAccount',
      'authorityHtmlElement': 'set_account.jsp',
      'orderNum': 710,
      'id': 32,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 701,
      'adminAuth': false,
      'authorityName': '积分管理',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'integralList',
      'authorityHtmlElement': 'integral_list.jsp',
      'orderNum': 710,
      'id': 61,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 701,
      'adminAuth': false,
      'authorityName': '抵现管理',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'integralTradeList',
      'authorityHtmlElement': 'integraltrade_list.jsp',
      'orderNum': 711,
      'id': 88,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 701,
      'adminAuth': false,
      'authorityName': '公司配置',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'companyConfig',
      'authorityHtmlElement': 'company_config.jsp',
      'orderNum': 712,
      'id': 130,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 701,
      'adminAuth': null,
      'authorityName': '组织架构设置',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'organizational',
      'authorityHtmlElement': 'organizational.jsp',
      'orderNum': 713,
      'id': 134,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 701,
      'adminAuth': false,
      'authorityName': '权限',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'ordinaryPermission',
      'authorityHtmlElement': 'set_ordinary_authority.jsp',
      'orderNum': 714,
      'id': 142,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 701,
      'adminAuth': false,
      'authorityName': '登录限制',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'loginRestriction',
      'authorityHtmlElement': 'login_restriction_authority.jsp',
      'orderNum': 716,
      'id': 148,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': null,
      'adminAuth': false,
      'authorityName': '订货配置',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'suppulierRoot',
      'authorityHtmlElement': null,
      'orderNum': 801,
      'id': 131,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 801,
      'adminAuth': false,
      'authorityName': '订货供应配置',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'supplierConfig',
      'authorityHtmlElement': 'supplier_config.jsp',
      'orderNum': 802,
      'id': 119,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 801,
      'adminAuth': false,
      'authorityName': '多规格商品配置',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'supplierMultspec',
      'authorityHtmlElement': 'supplier_multspec.jsp',
      'orderNum': 803,
      'id': 120,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': null,
      'adminAuth': false,
      'authorityName': '商城设置',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'mallRoot',
      'authorityHtmlElement': null,
      'orderNum': 901,
      'id': 51,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 901,
      'adminAuth': false,
      'authorityName': '发布商品',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'mallPublishProduct',
      'authorityHtmlElement': 'publish_product.jsp',
      'orderNum': 902,
      'id': 52,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 901,
      'adminAuth': false,
      'authorityName': '设置模板',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'mallModel',
      'authorityHtmlElement': 'template_list.jsp,mall_model.jsp',
      'orderNum': 903,
      'id': 53,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 901,
      'adminAuth': false,
      'authorityName': '预订订单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'appointment',
      'authorityHtmlElement': 'appointment_order_list.jsp,appointment_order_detail.jsp',
      'orderNum': 904,
      'id': 92,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 901,
      'adminAuth': false,
      'authorityName': '预约订单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'book',
      'authorityHtmlElement': 'book_order_list.jsp, book_order_detail.jsp',
      'orderNum': 905,
      'id': 133,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 901,
      'adminAuth': false,
      'authorityName': '服务网点配置',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'reserveNetPointConfig',
      'authorityHtmlElement': 'reserve_netPoint_config.jsp',
      'orderNum': 906,
      'id': 135,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 901,
      'adminAuth': false,
      'authorityName': '公众号服务配置',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'reserveConfig',
      'authorityHtmlElement': 'reserve_config.jsp',
      'orderNum': 907,
      'id': 141,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': null,
      'adminAuth': false,
      'authorityName': '卡券管理',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'couponsRoot',
      'authorityHtmlElement': null,
      'orderNum': 1001,
      'id': 149,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1001,
      'adminAuth': false,
      'authorityName': '卡券模板列表',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'couponsTemplate',
      'authorityHtmlElement': 'coupons_template_list.jsp ',
      'orderNum': 1002,
      'id': 150,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1001,
      'adminAuth': false,
      'authorityName': '卡券模板编辑',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'couponsTemplateEdit',
      'authorityHtmlElement': 'coupons_template_edit.jsp',
      'orderNum': 1003,
      'id': 151,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1001,
      'adminAuth': false,
      'authorityName': '卡券列表',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'couponsList',
      'authorityHtmlElement': 'coupons_list.jsp',
      'orderNum': 1004,
      'id': 152,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1001,
      'adminAuth': false,
      'authorityName': '卡券发放',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'couponsGrant',
      'authorityHtmlElement': 'coupons_grant.jsp',
      'orderNum': 1005,
      'id': 153,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1001,
      'adminAuth': false,
      'authorityName': '卡券详情',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'couponsDetails',
      'authorityHtmlElement': 'coupons_details.jsp',
      'orderNum': 1006,
      'id': 154,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': null,
      'adminAuth': false,
      'authorityName': '加工与检验',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'proccessRoot',
      'authorityHtmlElement': null,
      'orderNum': 1151,
      'id': 98,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1151,
      'adminAuth': false,
      'authorityName': '订单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'proccessOrder',
      'authorityHtmlElement': 'proccess_order.jsp',
      'orderNum': 1152,
      'id': 99,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 1151,
      'adminAuth': false,
      'authorityName': '业绩',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'proccessAchievement',
      'authorityHtmlElement': 'proccess_achievement.jsp',
      'orderNum': 1153,
      'id': 100,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': null,
      'adminAuth': false,
      'authorityName': '积分商城',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'integralMallRoot',
      'authorityHtmlElement': null,
      'orderNum': 1201,
      'id': 165,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1201,
      'adminAuth': false,
      'authorityName': '商品列表',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'integralMallGoods',
      'authorityHtmlElement': 'integral_mall_goods.jsp',
      'orderNum': 1202,
      'id': 166,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1201,
      'adminAuth': false,
      'authorityName': '商品详情',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'integralMallGoodsDetail',
      'authorityHtmlElement': 'integral_mall_goods_detail.jsp',
      'orderNum': 1203,
      'id': 169,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1201,
      'adminAuth': false,
      'authorityName': '兑换记录',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'integralMallExchange',
      'authorityHtmlElement': 'integral_mall_exchange.jsp',
      'orderNum': 1204,
      'id': 167,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1201,
      'adminAuth': false,
      'authorityName': '兑换详情',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'integralMallExchangeDetail',
      'authorityHtmlElement': 'integral_mall_exchange_detail.jsp',
      'orderNum': 1205,
      'id': 170,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1201,
      'adminAuth': false,
      'authorityName': '全局设置',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'integralMallGlobal',
      'authorityHtmlElement': 'integral_mall_global.jsp',
      'orderNum': 1206,
      'id': 171,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': null,
      'adminAuth': false,
      'authorityName': '采购',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'purchaseRoot',
      'authorityHtmlElement': null,
      'orderNum': 1301,
      'id': 104,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1301,
      'adminAuth': false,
      'authorityName': '新建采购单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'stockNewOffLine',
      'authorityHtmlElement': 'order_detail_for_stock.jsp',
      'orderNum': 1302,
      'id': 14,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 1301,
      'adminAuth': false,
      'authorityName': '新建采购退货单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'stockRetreatNewOffLine',
      'authorityHtmlElement': 'order_detail_stock_retreat.jsp',
      'orderNum': 1303,
      'id': 71,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 1301,
      'adminAuth': false,
      'authorityName': '采购入库单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'stockOffLine',
      'authorityHtmlElement': 'stock.jsp',
      'orderNum': 1304,
      'id': 12,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 1301,
      'adminAuth': false,
      'authorityName': '采购退货单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'stockRetreatOffLine',
      'authorityHtmlElement': 'stock_retreat.jsp',
      'orderNum': 1305,
      'id': 75,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': null,
      'adminAuth': false,
      'authorityName': '线上采购',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'purchaseRootOnLine',
      'authorityHtmlElement': null,
      'orderNum': 1401,
      'id': 105,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1401,
      'adminAuth': false,
      'authorityName': '新建采购单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'stockNewOnLine',
      'authorityHtmlElement': 'order_detail_for_stock.jsp',
      'orderNum': 1402,
      'id': 106,
      'check': false,
      'leaf': true,
      'parameters': '{sup:\'ONLINE\'}'
    },
    {
      'parentOrderNum': 1401,
      'adminAuth': false,
      'authorityName': '新建采购退货单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'stockRetreatNewOnLine',
      'authorityHtmlElement': 'order_detail_stock_retreat.jsp',
      'orderNum': 1403,
      'id': 107,
      'check': false,
      'leaf': true,
      'parameters': '{sup:\'ONLINE\'}'
    },
    {
      'parentOrderNum': 1401,
      'adminAuth': false,
      'authorityName': '采购入库单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'stockOnLine',
      'authorityHtmlElement': 'stock.jsp',
      'orderNum': 1404,
      'id': 108,
      'check': false,
      'leaf': true,
      'parameters': '{sup:\'ONLINE\'}'
    },
    {
      'parentOrderNum': 1401,
      'adminAuth': false,
      'authorityName': '采购退货单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'stockRetreatOnLine',
      'authorityHtmlElement': 'stock_retreat.jsp',
      'orderNum': 1405,
      'id': 109,
      'check': false,
      'leaf': true,
      'parameters': '{sup:\'ONLINE\'}'
    },
    {
      'parentOrderNum': null,
      'adminAuth': false,
      'authorityName': '调拨',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'requisitionRoot',
      'authorityHtmlElement': null,
      'orderNum': 1501,
      'id': 110,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1501,
      'adminAuth': false,
      'authorityName': '新建调拨出库单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'inventoryOutNew',
      'authorityHtmlElement': 'order_detail_for_inventory.jsp',
      'orderNum': 1502,
      'id': 111,
      'check': false,
      'leaf': false,
      'parameters': '{type:\'INVENTORY_OUT\'}'
    },
    {
      'parentOrderNum': 1501,
      'adminAuth': false,
      'authorityName': '调拨出库单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'inventoryOutOrder',
      'authorityHtmlElement': 'inventory_mgr.jsp',
      'orderNum': 1503,
      'id': 112,
      'check': false,
      'leaf': false,
      'parameters': '{type:\'INVENTORY_OUT\'}'
    },
    {
      'parentOrderNum': 1501,
      'adminAuth': false,
      'authorityName': '调拨入库单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'inventoryInOrder',
      'authorityHtmlElement': 'inventory_mgr.jsp',
      'orderNum': 1504,
      'id': 113,
      'check': false,
      'leaf': false,
      'parameters': '{type:\'INVENTORY_IN\'}'
    },
    {
      'parentOrderNum': null,
      'adminAuth': false,
      'authorityName': '盘点',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'inventoryCheckRoot',
      'authorityHtmlElement': null,
      'orderNum': 1601,
      'id': 114,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1601,
      'adminAuth': false,
      'authorityName': '库存盘点',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'inventoryCheck',
      'authorityHtmlElement': 'inventory_check.jsp',
      'orderNum': 1602,
      'id': 65,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1601,
      'adminAuth': false,
      'authorityName': '盘点出库单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'inventoryCheckOut',
      'authorityHtmlElement': 'inventory_mgr.jsp',
      'orderNum': 1603,
      'id': 115,
      'check': false,
      'leaf': false,
      'parameters': '{type:\'CHECK_OUT\'}'
    },
    {
      'parentOrderNum': 1601,
      'adminAuth': false,
      'authorityName': '盘点入库单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'inventoryCheckIn',
      'authorityHtmlElement': 'inventory_mgr.jsp',
      'orderNum': 1604,
      'id': 116,
      'check': false,
      'leaf': false,
      'parameters': '{type:\'CHECK_IN\'}'
    },
    {
      'parentOrderNum': 1601,
      'adminAuth': false,
      'authorityName': '盘点记录单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'inventoryRecord',
      'authorityHtmlElement': 'inventory_record_list.jsp,inventory_check_notes.jsp',
      'orderNum': 1605,
      'id': 140,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1,
      'adminAuth': false,
      'authorityName': '制单',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'createOrder',
      'authorityHtmlElement': null,
      'orderNum': 1701,
      'id': 101,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1,
      'adminAuth': false,
      'authorityName': '审核',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'auditOrder',
      'authorityHtmlElement': null,
      'orderNum': 1702,
      'id': 102,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1,
      'adminAuth': false,
      'authorityName': '收款记录删除权限',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'payInfoDelete',
      'authorityHtmlElement': null,
      'orderNum': 1703,
      'id': 122,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1,
      'adminAuth': false,
      'authorityName': '批量修改商品价格权限',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'batchModifyAllPrice',
      'authorityHtmlElement': null,
      'orderNum': 1704,
      'id': 96,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1,
      'adminAuth': false,
      'authorityName': '数据导入',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'dataImport',
      'authorityHtmlElement': 'data_import.jsp',
      'orderNum': 1705,
      'id': 74,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1,
      'adminAuth': false,
      'authorityName': '考勤',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'attendanceSheetRoot',
      'authorityHtmlElement': null,
      'orderNum': 1706,
      'id': 124,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1,
      'adminAuth': false,
      'authorityName': '管理者权限',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'shopkeeper',
      'authorityHtmlElement': null,
      'orderNum': 1706,
      'id': 155,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 1,
      'adminAuth': false,
      'authorityName': '考勤机管理',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'attendanceManagement',
      'authorityHtmlElement': 'attendance_management.jsp',
      'orderNum': 1707,
      'id': 127,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 1,
      'adminAuth': false,
      'authorityName': '考勤记录',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'attendanceSheet',
      'authorityHtmlElement': 'attendance_sheet.jsp',
      'orderNum': 1708,
      'id': 125,
      'check': false,
      'leaf': true,
      'parameters': null
    },
    {
      'parentOrderNum': 2,
      'adminAuth': false,
      'authorityName': '进货价查看设置',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'stockPriceRoot',
      'authorityHtmlElement': null,
      'orderNum': 1801,
      'id': 45,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 2,
      'adminAuth': false,
      'authorityName': '商品进货价',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'stockPriceOnProduct',
      'authorityHtmlElement': null,
      'orderNum': 1802,
      'id': 46,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 2,
      'adminAuth': false,
      'authorityName': '订单进货价',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'stockPriceOnOrder',
      'authorityHtmlElement': null,
      'orderNum': 1803,
      'id': 47,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 2,
      'adminAuth': false,
      'authorityName': '库存进货价',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'stockPriceOnInventory',
      'authorityHtmlElement': null,
      'orderNum': 1804,
      'id': 48,
      'check': false,
      'leaf': false,
      'parameters': null
    },
    {
      'parentOrderNum': 2,
      'adminAuth': false,
      'authorityName': '商品管理中的供应商权限',
      'confirmOperation': null,
      'reg': null,
      'authorityCode': 'supplierView',
      'authorityHtmlElement': null,
      'orderNum': 1805,
      'id': 139,
      'check': false,
      'leaf': false,
      'parameters': null
    }
    */
];

Array.prototype.contains = function(obj) {
  let i = this.length;
  if (!i) {
    while (i--) {
      if (this[i] === obj) {
        return true;
      }
    }
  }
  return false;
};

function getAuths(auths) {
  let sortAuths = [];
  auths.forEach(obj => {
    if (
      /* obj.parentOrderNum !== null &&
            obj.parentOrderNum !== undefined && */
      obj.parentOrderNum !== 1 &&
      obj.parentOrderNum !== 2) {
      sortAuths.push(obj);
    }
  });
  return sortAuths;
}

exports.state = {
  auths: getAuths(auths)
};